import json
import os
import subprocess


def get_newlib_include():
    """Find the riscv32-esp-elf newlib include directory."""
    # Primary: ask gcc directly
    try:
        result = subprocess.run(
            ["riscv32-esp-elf-gcc", "-print-sysroot"], capture_output=True, text=True
        )
        sysroot = result.stdout.strip()
        candidate = os.path.join(sysroot, "include")
        if os.path.isdir(candidate):
            return candidate
    except Exception:
        pass

    # Fallback: scan ~/.espressif/tools/riscv32-esp-elf/ for newest version
    tools_dir = os.path.join(
        os.environ.get("IDF_TOOLS_PATH", os.path.expanduser("~/.espressif")),
        "tools",
        "riscv32-esp-elf",
    )
    if os.path.isdir(tools_dir):
        for version in sorted(os.listdir(tools_dir), reverse=True):
            candidate = os.path.join(
                tools_dir, version, "riscv32-esp-elf", "riscv32-esp-elf", "include"
            )
            if os.path.isdir(candidate):
                return candidate

    return ""


def get_newlib_platform():
    idf_path = os.environ.get("IDF_PATH", "")
    if not idf_path:
        # idf.py sometimes sets this instead
        idf_path = os.environ.get("IDF_PATH_OVERRIDE", "")
    if not idf_path:
        # last resort: derive from the compile_commands.json paths themselves
        # any path containing esp-idf/components tells us where IDF lives
        try:
            with open("build/compile_commands.json", "r") as f:
                sample = f.read(4096)
            import re

            m = re.search(r'(/[^\s"]+/esp-idf)/components', sample)
            if m:
                idf_path = m.group(1)
        except Exception:
            pass
    if idf_path:
        candidate = os.path.join(idf_path, "components", "newlib", "platform_include")
        if os.path.isdir(candidate):
            return candidate
    return ""


def generate():
    try:
        with open("build/compile_commands.json", "r") as f:
            commands = json.load(f)

        include_paths = set()
        for cmd in commands:
            parts = cmd["command"].split()
            for i, part in enumerate(parts):
                if part.startswith("-I"):
                    include_paths.add(part[2:].strip())
                elif part in (
                    "-isystem",
                    "-iwithprefix",
                    "-iwithprefixbefore",
                ) and i + 1 < len(parts):
                    include_paths.add(parts[i + 1].strip())

        newlib_include = get_newlib_include()
        newlib_platform = get_newlib_platform()

        if not newlib_include:
            print("WARNING: could not find riscv32-esp-elf newlib include dir")
        if not newlib_platform:
            print("WARNING: could not find newlib/platform_include — is IDF_PATH set?")

        def clean(p):
            return p.replace("\\", "/")

        with open("main/paths.zig", "w") as f:
            f.write(
                "// Auto-generated by generate_paths.py — do not edit, do not commit\n"
            )
            f.write(f'pub const newlib_include = "{clean(newlib_include)}";\n')
            f.write(f'pub const newlib_platform = "{clean(newlib_platform)}";\n')
            f.write("\n")
            f.write("pub const include_paths = &[_][]const u8{\n")
            for path in sorted(include_paths):
                f.write(f'    "{clean(path)}",\n')
            f.write("};\n")

        print("Successfully generated main/paths.zig")

    except Exception as e:
        print(f"Error generating paths: {e}")
        raise


if __name__ == "__main__":
    generate()
